# Makefile for Task 2

CXX = g++
CXXFLAGS = -std=c++11 -Wall -pedantic -O3 # -ffast-math -march=native

all: stenciljacobi

stenciljacobi: header.hpp stenciljacobi.cpp
	$(CXX) stenciljacobi.cpp -o stenciljacobi $(CXXFLAGS)


